name: Windows Wheels
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10", "3.11"]
        bitness: [32, 64]
    env:
      NASM_VERSION: 2.15.05
      GMAKE_VERSION: 3.81
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8 # to run script

      - name: Setup Visual C++
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
          toolset: 14.0

      - name: Test
        run: env

      - name: Cache multiple paths
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: |
            C:\dev
          key: ${{ hashFiles('winbuild.py') }}-${{ matrix.bitness }}

      - name: Install Nasm
        if: steps.cache-deps.outputs.cache-hit != 'true'
        shell: pwsh
        run: |
          curl.exe -OL "https://www.nasm.us/pub/nasm/releasebuilds/$($env:NASM_VERSION)/win64/nasm-$($env:NASM_VERSION)-win64.zip"
          7z x nasm-$($env:NASM_VERSION)-win64.zip -oC:/dev/nasm
          echo "C:\dev\nasm\nasm-$($env:NASM_VERSION)" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Install Gmake
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: |
          curl.exe -OL "https://downloads.sourceforge.net/project/gnuwin32/make/$($env:GMAKE_VERSION)/make-$($env:GMAKE_VERSION)-bin.zip"
          7z x make-$($env:GMAKE_VERSION)-bin.zip -oC:/dev/Gmake
          curl.exe -OL https://downloads.sourceforge.net/project/gnuwin32/make/$($env:GMAKE_VERSION)/make-$($env:GMAKE_VERSION)-dep.zip
          7z x make-$($env:GMAKE_VERSION)-dep.zip -oC:/dev/Gmake
          echo "C:\dev\Gmake\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Build Dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: |
          python winbuild.py builddeps -b ${{ matrix.bitness }} -p ${{ matrix.python-version }}

      - name: Download Python
        run: |
          python winbuild.py downloadpy -b ${{ matrix.bitness }} -p ${{ matrix.python-version }}

      - name: Assemble Deps
        run: |
          python winbuild.py assembledeps -b ${{ matrix.bitness }} -p ${{ matrix.python-version }}

      - uses: actions/upload-artifact@v3
        with:
          name: deps-${{ matrix.bitness }}-${{ matrix.python-version }}
          path: deps/*.zip

      - name: Copy CheckOut
        shell: bash
        run: |
          cp -r $GITHUB_WORKSPACE 'c:/dev'

      - name: List
        shell: pwsh
        run: |
          Get-ChildItem -Recurse -Path c:/dev/ | Where { ! $_.PSIsContainer } | Select FullName,Length | Format-Table -AutoSize

      - name: Build Wheels
        run: |
          python winbuild.py -b ${{ matrix.bitness }} -p ${{ matrix.python-version }}

      - name: Assemble Wheels
        run: |
          python winbuild.py assemble -b ${{ matrix.bitness }} -p ${{ matrix.python-version }}

      - name: Test Wheels
        run: |
          python winbuild.py test -b ${{ matrix.bitness }} -p ${{ matrix.python-version }}

      - uses: actions/upload-artifact@v3
        with:
          name: dist-${{ matrix.bitness }}-${{ matrix.python-version }}
          path: dist/*
